# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e72xeXHvphja-JRLjyLe1COgPtE98Rwu
"""

print('Hello')

